---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.docker
    version: 4.6.2
  - name: community.general
    version: 11.1.2
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s
    version: v3.5.0
