---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.docker
    version: 4.8.0
  - name: community.general
    version: 11.3.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s
    version: v3.6.1
