---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: firefly-iii
    repo: https://firefly-iii.github.io/kubernetes
    version: 1.9.12
    releaseName: &releaseName firefly-iii
    namespace: &releaseNamespace default
    valuesFile: values.yml
commonAnnotations:
  meta.helm.sh/release-name: *releaseName
  meta.helm.sh/release-namespace: *releaseNamespace
  nfs.io/storage-path: "firefly_iii_uploads"
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: Helm
